SYNCQT.HEADER_FILES = ../../include/QtBZip2/QtBZip2 ../../include/QtBZip2/qtbzip2.h
SYNCQT.HEADER_CLASSES = ../../include/QtBZip2/QtBZip2
SYNCQT.PRIVATE_HEADER_FILES =
SYNCQT.QPA_HEADER_FILES = 
SYNCQT.INJECTIONS = 
